import { Client, Property, Recommendation, Interaction, DashboardMetrics } from "@/types";

export const mockClients: Client[] = [
  {
    id: "1",
    name: "John Smith",
    email: "john.smith@email.com",
    phone: "+1 (555) 123-4567",
    budgetRange: { min: 500000, max: 700000 },
    status: "pending",
    createdAt: "2024-11-20",
    preferences: {
      bedrooms: 3,
      bathrooms: 2,
      location: "Palo Alto",
      propertyType: "House",
    },
    notes: "Looking for family home with good schools nearby.",
  },
  {
    id: "2",
    name: "Sarah Johnson",
    email: "sarah.j@email.com",
    phone: "+1 (555) 234-5678",
    budgetRange: { min: 800000, max: 1000000 },
    status: "recommended",
    createdAt: "2024-11-19",
    preferences: {
      bedrooms: 4,
      bathrooms: 3,
      location: "Mountain View",
      propertyType: "House",
    },
  },
  {
    id: "3",
    name: "Mike Chen",
    email: "mike.chen@email.com",
    phone: "+1 (555) 345-6789",
    budgetRange: { min: 600000, max: 750000 },
    status: "in_progress",
    createdAt: "2024-11-18",
    preferences: {
      bedrooms: 3,
      bathrooms: 2,
      location: "Sunnyvale",
      propertyType: "House",
    },
  },
  {
    id: "4",
    name: "Emily Davis",
    email: "emily.d@email.com",
    phone: "+1 (555) 456-7890",
    budgetRange: { min: 400000, max: 550000 },
    status: "pending",
    createdAt: "2024-11-17",
    preferences: {
      bedrooms: 2,
      bathrooms: 1,
      location: "San Jose",
      propertyType: "Condo",
    },
  },
  {
    id: "5",
    name: "David Wilson",
    email: "david.w@email.com",
    phone: "+1 (555) 567-8901",
    budgetRange: { min: 900000, max: 1200000 },
    status: "recommended",
    createdAt: "2024-11-15",
    preferences: {
      bedrooms: 5,
      bathrooms: 4,
      location: "Los Altos",
      propertyType: "House",
    },
  },
];

export const mockProperties: Property[] = [
  {
    id: "p1",
    address: "123 Oak Street",
    city: "Palo Alto",
    state: "CA",
    price: 650000,
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1800,
    imageUrl: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&h=600&fit=crop",
    matchScore: 95,
    propertyType: "House",
    yearBuilt: 2015,
    description: "Beautiful family home in excellent neighborhood",
    agentNotes: "Great school district, recently renovated kitchen",
    agentTags: ["family-friendly", "good-schools", "renovated"],
    agentRating: 5,
    isFavorite: true,
    viewCount: 12,
    lastViewed: "2024-11-20",
  },
  {
    id: "p2",
    address: "456 Pine Ave",
    city: "Mountain View",
    state: "CA",
    price: 680000,
    bedrooms: 4,
    bathrooms: 2.5,
    squareFeet: 2200,
    imageUrl: "https://images.unsplash.com/photo-1568605117032-2721fed0a54c?w=800&h=600&fit=crop",
    matchScore: 92,
    propertyType: "House",
    yearBuilt: 2018,
    description: "Spacious modern home with updated kitchen",
    agentNotes: "Open house scheduled for this weekend",
    agentTags: ["modern", "spacious"],
    agentRating: 4,
    viewCount: 8,
    lastViewed: "2024-11-19",
  },
  {
    id: "p3",
    address: "789 Elm Road",
    city: "Sunnyvale",
    state: "CA",
    price: 620000,
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1700,
    imageUrl: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&h=600&fit=crop",
    matchScore: 88,
    propertyType: "House",
    yearBuilt: 2012,
    description: "Charming home with great curb appeal",
    agentNotes: "Needs some updates but good value",
    agentTags: ["charming", "value"],
    agentRating: 3,
    viewCount: 5,
    lastViewed: "2024-11-18",
  },
  {
    id: "p4",
    address: "321 Maple Drive",
    city: "Palo Alto",
    state: "CA",
    price: 720000,
    bedrooms: 3,
    bathrooms: 2.5,
    squareFeet: 2000,
    imageUrl: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
    matchScore: 90,
    propertyType: "House",
    yearBuilt: 2016,
    agentNotes: "Premium location, high demand area",
    agentTags: ["premium", "high-demand"],
    agentRating: 5,
    isFavorite: true,
    viewCount: 15,
    lastViewed: "2024-11-20",
  },
  {
    id: "p5",
    address: "654 Cedar Lane",
    city: "Mountain View",
    state: "CA",
    price: 750000,
    bedrooms: 4,
    bathrooms: 3,
    squareFeet: 2400,
    imageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
    matchScore: 85,
    propertyType: "House",
    yearBuilt: 2019,
    agentNotes: "New construction, energy efficient",
    agentTags: ["new-construction", "energy-efficient"],
    agentRating: 4,
    viewCount: 10,
    lastViewed: "2024-11-19",
  },
  {
    id: "p6",
    address: "890 Birch Street",
    city: "Sunnyvale",
    state: "CA",
    price: 580000,
    bedrooms: 2,
    bathrooms: 2,
    squareFeet: 1400,
    imageUrl: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
    matchScore: 82,
    propertyType: "Condo",
    yearBuilt: 2020,
    description: "Modern condo with great amenities",
    agentNotes: "Perfect for first-time buyers",
    agentTags: ["condo", "first-time-buyer"],
    agentRating: 4,
    viewCount: 6,
    lastViewed: "2024-11-17",
  },
  {
    id: "p7",
    address: "567 Willow Court",
    city: "San Jose",
    state: "CA",
    price: 550000,
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1600,
    imageUrl: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop",
    matchScore: 80,
    propertyType: "Townhouse",
    yearBuilt: 2014,
    description: "Well-maintained townhouse in quiet neighborhood",
    agentNotes: "HOA includes landscaping and pool",
    agentTags: ["townhouse", "hoa"],
    agentRating: 3,
    viewCount: 4,
    lastViewed: "2024-11-16",
  },
  {
    id: "p8",
    address: "234 Spruce Avenue",
    city: "Los Altos",
    state: "CA",
    price: 950000,
    bedrooms: 5,
    bathrooms: 4,
    squareFeet: 2800,
    imageUrl: "https://images.unsplash.com/photo-1600585154084-4e5fe7c39198?w=800&h=600&fit=crop",
    matchScore: 92,
    propertyType: "House",
    yearBuilt: 2017,
    description: "Luxury home with pool and large yard",
    agentNotes: "Premium property, multiple offers expected",
    agentTags: ["luxury", "pool", "large-yard"],
    agentRating: 5,
    isFavorite: true,
    viewCount: 20,
    lastViewed: "2024-11-20",
  },
];

export const mockRecommendations: Recommendation[] = [
  {
    id: "r1",
    clientId: "1",
    clientName: "John Smith",
    properties: [mockProperties[0], mockProperties[1], mockProperties[2]],
    createdAt: "2024-11-20",
    status: "sent",
  },
  {
    id: "r2",
    clientId: "2",
    clientName: "Sarah Johnson",
    properties: [mockProperties[1], mockProperties[4]],
    createdAt: "2024-11-19",
    status: "viewed",
  },
];

export const mockInteractions: Interaction[] = [
  {
    id: "i1",
    clientId: "1",
    type: "call",
    title: "Initial consultation call",
    description: "Discussed budget, preferences, and timeline",
    createdAt: "2024-11-20T10:00:00Z",
    createdBy: "Agent",
  },
  {
    id: "i2",
    clientId: "1",
    type: "recommendation_sent",
    title: "Property recommendations sent",
    description: "Sent 3 property recommendations via email",
    createdAt: "2024-11-20T14:30:00Z",
    createdBy: "System",
  },
  {
    id: "i3",
    clientId: "2",
    type: "meeting",
    title: "Property viewing scheduled",
    description: "Scheduled viewing for 456 Pine Ave on Nov 22",
    createdAt: "2024-11-19T16:00:00Z",
    createdBy: "Agent",
  },
  {
    id: "i4",
    clientId: "3",
    type: "email",
    title: "Follow-up email sent",
    description: "Sent follow-up regarding property preferences",
    createdAt: "2024-11-18T09:15:00Z",
    createdBy: "Agent",
  },
];

export const mockDashboardMetrics: DashboardMetrics = {
  activeClients: 24,
  activeClientsChange: 12,
  pendingMatches: 8,
  monthlyRecommendations: 156,
  monthlyRecommendationsChange: 28,
  matchSuccessRate: 87,
  matchSuccessRateChange: 5,
};

